server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: booking-service
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/booking-db;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
